### PR TITLE
added assertions to test ForwardCurrentMessageTo

### PR DESCRIPTION
**Pull request by timbussmann**
related to #26

### CODE REVIEW

**Comment by timbussmann** [comment]
@Particular/engineers please review

**Comment by DavidBoike** [comment]
:+1:

**Comment by danielmarbach** [comment]
Could we use `Assert.Throws` instead of `ExpectedException`?

**Comment by timbussmann** [comment]
@danielmarbach While I prefer `Assert.Throws` too, is there a real value in touch all these tests?

**Comment by danielmarbach** [comment]
Yes. Alignment :D

On Mon, Oct 26, 2015 at 2:54 PM, Tim Bussmann <notifications@github.com>
wrote:

> @danielmarbach <https://github.com/danielmarbach> While I prefer
> Assert.Throws too, is there a real value in touch all these tests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.Testing/pull/27#issuecomment-151140664>
> .
>



-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by timbussmann** [comment]
just can't say no to @danielmarbach's yaks

**Comment by danielmarbach** [comment]
You can also do it in a seperate PR. But since you added new tests I think it is good to change it in this PR

**Comment by danielmarbach** [comment]
And some Yaks have to be shaved ;)

**Comment by timbussmann** [comment]
@danielmarbach it's already done.

**Pull request merged**
