### PR TITLE
Add apache 2 license for ServiceCollection.cs

### PR DESCRIPTION
**Pull request by timbussmann**
the same way as currently done in Core.

### CODE REVIEW

**Review by mauroservienti — APPROVED** [review]

**Comment by udidahan** [comment]
Do we have guidelines somewhere (Risk maybe) that define when to use which kind of license for source code?

**Comment by mauroservienti** [comment]
We do

**Comment by timbussmann** [comment]
@udidahan we do have the following (internal) document about licenses: https://github.com/Particular/PlatformArchitecture/blob/master/documentation/oss-licenses.md. Keep in mind that this project remains under our standard-license, it just adds the Apache 2 license as required by the license term as an artifact to be redistributed along with the Apache 2.0 licensed file this repo contains.

**Comment by udidahan** [comment]
OK - thanks. I understand now.

**Pull request merged**
