### PR TITLE
[SPIKE] Expect fails

### PR DESCRIPTION
**Pull request by danielmarbach**
would solve https://github.com/Particular/NServiceBus.Testing/issues/90

@Particular/nservicebus-maintainers is this something worth pursuing?

### CODE REVIEW

**Comment by timbussmann** [comment]
Personally I'm on the fence about adding new features to the testing framework itself.

**Comment by timbussmann** [comment]
@danielmarbach any new thoughts on this? Do you want to finish this one up or close it?

**Comment by danielmarbach** [comment]
I have no capacity to move this forward

**Comment by timbussmann** [comment]
> I have no capacity to move this forward

do you feel that we should provide this? I'm happy to bring this up to discussion on a maintainer sync and see who's able to pick this up in case we want to do it, but as I don't see much value out of this API atm, I need someone advocating for this feature ;)

**Pull request closed without merging**
