### PR TITLE
Update to latest fakes.sources package

### PR DESCRIPTION
**Pull request by timbussmann**
Connects to #29 
Removed obsolete `NServiceBus.Fakes.Sources` package with `NServiceBus.Testing.Fakes.Sources`

@Particular/nservicebus-maintainers @mat-mcloughlin @WojcikMike  ping

### CODE REVIEW

**Comment by mat-mcloughlin** [comment]
Looks good to me!

**Comment by danielmarbach** [comment]
Didn't even have a chance to look at it. So when you pinged @Particular/nservicebus-maintainers you actually pinged yourself @timbussmann  :dancers:

**Comment by timbussmann** [comment]
@danielmarbach it was kinda blocking us and since it was just updating nugets I decided to pull it in after a few hours

**Comment by danielmarbach** [comment]
Yeah sorry. I was joking. Was really occupied with the releasing

**Pull request merged**
