### PR TITLE
[WIP] Update to NServiceBus 6.1.0

### PR DESCRIPTION
**Pull request by danielmarbach**

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers please review

**Comment by andreasohlund** [comment]
Do we merge this now or wait for the stable version?

**Comment by andreasohlund** [comment]
Yea, so we should mark all the prs WIP?

**Comment by timbussmann** [comment]
this hasn't been updated for a while. We could
* Update the PR to 6.1
* Only update the tests to 6.1, keep the package itself compiled against 6.0
* Close the PR, keep compiling against 6.0

My vote goes for option 3. Thoughts @danielmarbach ?

**Comment by danielmarbach** [comment]
Option 3 is good for me
Can you go ahead?
Tim Bussmann <notifications@github.com> schrieb am Mo. 20. Feb. 2017 um
14:05:

**Pull request closed without merging**
